"""empty message

Revision ID: 082a1e482ade
Revises: d127f3705831
Create Date: 2024-03-07 23:32:56.067978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082a1e482ade'
down_revision = 'd127f3705831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
