"""empty message

Revision ID: 937e32f892fc
Revises: b3cb40352090
Create Date: 2024-03-08 13:14:39.225149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937e32f892fc'
down_revision = 'b3cb40352090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('seeking_description')

    # ### end Alembic commands ###
